### PR TITLE
#58 done

### LINKED ISSUE #37: [Flag] Fall damage flag
A flag for if fall damage should be applied

### LINKED ISSUE #58: [Flag] No Attack Damage
Removes the ability for damage to be done via a attack of another entity

### LINKED ISSUE #93: [Bug] Enabling/Disabling itemframe crash
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> Crash report

## How to reproduce?

>> running either ``/zone region flag interact itemframe enable/disable``

### Crash report?

```txt
org.spongepowered.configurate.serialize.SerializationException: []: org.spongepowered.configurate.serialize.SerializationException: [Flags, zones, itemframe_interact, Enabled] of type java.util.Optional: No serializer available for type class java.util.Optional
        at org.zone.region.ZoneManager.save(ZoneManager.java:261)
        at org.zone.region.Zone.save(Zone.java:257)
        at org.zone.commands.structure.region.flags.interact.itemframe.ZoneFlagInteractItemframesEnableDisableCommand.run(ZoneFlagInteractItemframesEnableDisableCommand.java:58)
        at org.zone.commands.structure.ZoneSpongeCommand.process(ZoneSpongeCommand.java:111)
        at org.spongepowered.common.command.registrar.SpongeRawCommandRegistrar.process(SpongeRawCommandRegistrar.java:90)
        at org.spongepowered.vanilla.launch.command.VanillaCommandManager.processCommand(VanillaCommandManager.java:46)
        at org.spongepowered.common.command.manager.SpongeCommandManager.process(SpongeCommandManager.java:357)
        at org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.execute(SpongeCommandDispatcher.java:126)
        at org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.execute(DelegatingCommandDispatcher.java:70)
        at org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.execute(DelegatingCommandDispatcher.java:45)
        at net.minecraft.commands.Commands.performCommand(SourceFile:249)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(SourceFile:1211)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(SourceFile:1198)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(SourceFile:1177)
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(SourceFile:36)
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(SourceFile:9)
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:263)
        at net.minecraft.network.protocol.PacketUtils.mdb44925$lambda$tracker$redirectProcessPacket$0$0(SourceFile:552)
        at net.minecraft.server.TickTask.run(SourceFile:18)
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(SourceFile:144)
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(SourceFile:23)
        at net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapAndPerformContextSwitch(SourceFile:4348)
        at net.minecraft.server.MinecraftServer.doRunTask(SourceFile:761)
        at net.minecraft.server.MinecraftServer.doRunTask(SourceFile:155)
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(SourceFile:118)
        at net.minecraft.server.MinecraftServer.pollTaskInternal(SourceFile:743)
        at net.minecraft.server.MinecraftServer.pollTask(SourceFile:737)
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(SourceFile:127)
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(SourceFile:722)
        at net.minecraft.server.MinecraftServer.runServer(SourceFile:674)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(SourceFile:257)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.configurate.serialize.SerializationException: [Flags, zones, itemframe_interact, Enabled] of type java.util.Optional: No serializer available for type class java.util.Optional
        at org.spongepowered.configurate.ScopedConfigurationNode.set(ScopedConfigurationNode.java:120)
        at org.spongepowered.configurate.AbstractConfigurationNode.set(AbstractConfigurationNode.java:180)
        at org.spongepowered.configurate.AbstractConfigurationNode.set(AbstractConfigurationNode.java:43)
        at org.zone.region.flag.interact.itemframe.ItemFrameInteractFlagType.save(ItemFrameInteractFlagType.java:49)
        at org.zone.region.flag.interact.itemframe.ItemFrameInteractFlagType.save(ItemFrameInteractFlagType.java:13)
        at org.zone.region.flag.Flag.save(Flag.java:131)
        at org.zone.region.ZoneManager.save(ZoneManager.java:259)
        ... 31 more```

### LINKED ISSUE #94: [Bug] enabling/disabling player prevention causes crash
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> crash

## How to reproduce?

>> run enable/disable for player prevention

### Crash report?

```txt
ionException: [Flags, zones, preventplayers, Enabled] of type java.util.Optional: No serializer available for type class java.util.Optional
        at org.zone.region.ZoneManager.save(ZoneManager.java:261)
        at org.zone.region.Zone.save(Zone.java:257)
        at org.zone.commands.structure.region.flags.prevention.player.ZoneFlagPreventionPlayerEnableDisableCommand.run(ZoneFlagPreventionPlayerEnableDisableCommand.java:59)
        at org.zone.commands.structure.ZoneSpongeCommand.process(ZoneSpongeCommand.java:111)
        at org.spongepowered.common.command.registrar.SpongeRawCommandRegistrar.process(SpongeRawCommandRegistrar.java:90)
        at org.spongepowered.vanilla.launch.command.VanillaCommandManager.processCommand(VanillaCommandManager.java:46)
        at org.spongepowered.common.command.manager.SpongeCommandManager.process(SpongeCommandManager.java:357)
        at org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.execute(SpongeCommandDispatcher.java:126)
        at org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.execute(DelegatingCommandDispatcher.java:70)
        at org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.execute(DelegatingCommandDispatcher.java:45)
        at net.minecraft.commands.Commands.performCommand(SourceFile:249)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(SourceFile:1211)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(SourceFile:1198)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(SourceFile:1177)
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(SourceFile:36)
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(SourceFile:9)
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:263)
        at net.minecraft.network.protocol.PacketUtils.md45a90f$lambda$tracker$redirectProcessPacket$0$0(SourceFile:552)
        at net.minecraft.server.TickTask.run(SourceFile:18)
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(SourceFile:144)
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(SourceFile:23)
        at net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapAndPerformContextSwitch(SourceFile:4348)
        at net.minecraft.server.MinecraftServer.doRunTask(SourceFile:761)
        at net.minecraft.server.MinecraftServer.doRunTask(SourceFile:155)
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(SourceFile:118)
        at net.minecraft.server.MinecraftServer.pollTaskInternal(SourceFile:743)
        at net.minecraft.server.MinecraftServer.pollTask(SourceFile:737)
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(SourceFile:127)
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(SourceFile:722)
        at net.minecraft.server.MinecraftServer.runServer(SourceFile:674)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(SourceFile:257)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.configurate.serialize.SerializationException: [Flags, zones, preventplayers, Enabled] of type java.util.Optional: No serializer available for type class java.util.Optional
        at org.spongepowered.configurate.ScopedConfigurationNode.set(ScopedConfigurationNode.java:120)
        at org.spongepowered.configurate.AbstractConfigurationNode.set(AbstractConfigurationNode.java:180)
        at org.spongepowered.configurate.AbstractConfigurationNode.set(AbstractConfigurationNode.java:43)
        at org.zone.region.flag.move.player.preventing.PreventPlayersFlagType.save(PreventPlayersFlagType.java:48)
        at org.zone.region.flag.move.player.preventing.PreventPlayersFlagType.save(PreventPlayersFlagType.java:13)
        at org.zone.region.flag.Flag.save(Flag.java:131)
        at org.zone.region.ZoneManager.save(ZoneManager.java:259)
        ... 31 more
```

### PR DESCRIPTION
**Pull request by Lukamon24**
Closes #58

### CODE REVIEW

**Comment by Lukamon24** [comment]
Closes #37

File: src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import org.zone.region.flag.FlagType;
+import org.zone.region.flag.FlagTypes;
+import org.zone.region.group.key.GroupKey;
+import org.zone.region.group.key.GroupKeys;
+
+import java.util.Optional;
+
+public class EntityDamagePlayerFlag implements Flag.TaggedFlag, Flag.AffectsPlayer, Flag.Enabled {
+
+    public @Nullable Boolean enabled;
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java]: A tag flag should not hold data

File: src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    public static final EntityDamagePlayerFlag ELSE = new EntityDamagePlayerFlag(false);
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java]: No need for a static default when it comes to a tag flag

File: src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java (hunk 1 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java]: kay but wbt the cmd then

File: src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java (hunk 2 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java]: kay

File: src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+import org.jetbrains.annotations.Nullable;
+import org.zone.region.flag.Flag;
+import org.zone.region.flag.FlagType;
+import org.zone.region.flag.FlagTypes;
+import org.zone.region.group.key.GroupKey;
+import org.zone.region.group.key.GroupKeys;
+
+import java.util.Optional;
+
+public class EntityDamagePlayerFlag implements Flag.TaggedFlag, Flag.AffectsPlayer, Flag.Enabled {
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java]: A tag flag cannot hold data and therefore should not implement enabled too

Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlag.java]: k

File: src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlagListener.java [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+                .getPriorityZone(event.entity().world(), event.entity().position());
+        if (opZone.isEmpty()) {
+            return;
+        }
+
+        Zone zone = opZone.get();
+        Group group = zone.getMembers().getGroup(player.uniqueId());
+        if (group.contains(GroupKeys.ENTITY_DAMAGE_PLAYER)) {
+            return;
+         }
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlagListener.java]: I got it wrong before and you were right. You should cancel the event if the player has the permission

Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlagListener.java]: yes lol

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageFlag.java [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+import org.zone.region.flag.FlagTypes;
+import org.zone.region.flag.move.player.preventing.PreventPlayersFlag;
+import org.zone.region.group.key.GroupKey;
+import org.zone.region.group.key.GroupKeys;
+
+import java.util.Optional;
+
+public class PlayerFallDamageFlag implements Flag.TaggedFlag, Flag.Enabled, Flag.AffectsPlayer{
+
+    public @Nullable Boolean enabled;
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageFlag.java]: Tag flag cannot hold data

File: src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlagListener.java (hunk 4 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerFlagListener.java]: dats the reason i was weirded out lol

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageFlag.java (hunk 5 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageFlag.java]: meow ;c

Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageFlag.java]: emm what about the cmds? boolean arg? enable.... setEnabled...

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+                .getZoneManager()
+                .getPriorityZone(((Player) event).world(), ((Player) event).position());
+        if (opZone.isEmpty()) {
+            return;
+        }
+
+        Zone zone = opZone.get();
+        Group group = zone.getMembers().getGroup(player.uniqueId());
+        if (group.contains(GroupKeys.PLAYER_FALL_DAMAGE)) {
+            return;
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java]: In this listener there is nothing to state that its fall damage only that it prevents. While this would protect against fall damage. It would protect against all damage

File: src/main/java/org/zone/region/group/key/GroupKeys.java [hunk 7]
```diff
@@ -14,29 +13,31 @@
...
+    ENTITY_DAMAGE_PLAYER("entity_damage_player", "Prevent damage from any other entity"),
+    PLAYER_FALL_DAMAGE("player_fall_damage", "Prevent player  fall damage");
 
-    private final @NotNull String name;
-    private final @NotNull String key;
+    private final String name;
+    private final String key;
 
-    GroupKeys(@NotNull String key, @NotNull String name) {
+    GroupKeys(String key, String name) {
```
Comment (mosemister) [inline src/main/java/org/zone/region/group/key/GroupKeys.java]: Why was notnull removed?

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java (hunk 6 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java]: emm wut do thn

File: src/main/java/org/zone/region/group/key/GroupKeys.java (hunk 7 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/group/key/GroupKeys.java]: idk dude

Comment (Lukamon24) [reply src/main/java/org/zone/region/group/key/GroupKeys.java]: i didn't do it... i don't remember

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java (hunk 6 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java]: oh ok

**Comment by Lukamon24** [comment]
Link #37

File: pom.xml [hunk 8]
```diff
@@ -21,6 +21,19 @@
...
+                <groupId>org.apache.maven.plugins</groupId>
+                <artifactId>maven-shade-plugin</artifactId>
+                <version>3.1.0</version>
+                <executions>
+                    <execution>
+                        <phase>package</phase>
+                        <goals>
+                            <goal>shade</goal>
+                        </goals>
+                    </execution>
```
Comment (mosemister) [inline pom.xml]: erm .... why?

File: pom.xml [hunk 9]
```diff
@@ -94,6 +107,12 @@
             <version>1.3.0</version>
             <scope>provided</scope>
         </dependency>
+        <dependency>
+            <groupId>org.bstats</groupId>
+            <artifactId>bstats-sponge</artifactId>
+            <version>2.2.1</version>
```
Comment (mosemister) [inline pom.xml]: No, never bstats.

File: src/main/java/org/zone/region/group/key/GroupKeys.java (hunk 7 above)
Comment (mosemister) [reply src/main/java/org/zone/region/group/key/GroupKeys.java]: You may want to readd it

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageFlag.java (hunk 5 above)
Comment (mosemister) [reply src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageFlag.java]: No just remove the flag for disabled and add the flag for enabled

File: src/main/java/org/zone/commands/structure/region/flags/player/entitydamage/ZoneFlagEntityDamagePlayerEnableDisable.java [hunk 10]
```diff
@@ -0,0 +1,68 @@
...
+        Zone zone = commandContext.getArgument(this, ZONE_VALUE);
+        EntityDamagePlayerFlag entityDamagePlayerFlag = zone
+                .getFlag(FlagTypes.ENTITY_DAMAGE_PLAYER_FLAG_TYPE)
+                .orElse(new EntityDamagePlayerFlag());
+        if (enable) {
+            zone.addFlag(FlagTypes.ENTITY_DAMAGE_PLAYER_FLAG_TYPE.createCopyOfDefault());
+        }else {
+            zone.removeFlag(FlagTypes.ENTITY_DAMAGE_PLAYER_FLAG_TYPE);
+        }
+        zone.setFlag(entityDamagePlayerFlag);
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/player/entitydamage/ZoneFlagEntityDamagePlayerEnableDisable.java]: Remove set. Your logic for disable is to remove the flag and then add it back .... Logic is wrong

File: src/main/java/org/zone/commands/structure/region/flags/player/falldamage/ZoneFlagPlayerFallDamageEnableDisable.java [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+    }
+
+    @Override
+    public @NotNull CommandResult run(@NotNull CommandContext commandContext, @NotNull String... args) {
+        boolean enable = commandContext.getArgument(this, ENABLE_DISABLE);
+        Zone zone = commandContext.getArgument(this, ZONE_VALUE);
+        PlayerFallDamageFlag playerFallDamageFlag = zone
+                .getFlag(FlagTypes.PLAYER_FALL_DAMAGE_FLAG_TYPE)
+                .orElse(PlayerFallDamageFlag.ELSE);
+        playerFallDamageFlag.setEnabled(enable);
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/player/falldamage/ZoneFlagPlayerFallDamageEnableDisable.java]: Taggable flag should not have set enabled

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java [hunk 12]
```diff
@@ -0,0 +1,43 @@
...
+
+public class PlayerFallDamageListener {
+    @Listener
+    public void onPlayerFallDamageEvent(CollideBlockEvent.Fall event) {
+
+        if (!(event instanceof Player player)) {
+            return;
+        }
+
+        if (event.cause().first(DamageSource.class).isPresent()) {
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java]: If the cause isnt present then it should be returned too as the only case it wont have a damage source is either a forge mod or a sponge plugin trying to emulate the event and failing

File: pom.xml (hunk 9 above)
Comment (Lukamon24) [reply pom.xml]: Why

File: src/main/java/org/zone/commands/structure/region/flags/player/entitydamage/ZoneFlagEntityDamagePlayerEnableDisable.java (hunk 10 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/player/entitydamage/ZoneFlagEntityDamagePlayerEnableDisable.java]: Yea lol wondering

File: src/main/java/org/zone/commands/structure/region/flags/player/falldamage/ZoneFlagPlayerFallDamageEnableDisable.java (hunk 11 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/player/falldamage/ZoneFlagPlayerFallDamageEnableDisable.java]: Bruh

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java (hunk 12 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java]: .

File: pom.xml (hunk 9 above)
Comment (mosemister) [reply pom.xml]: Because peoples data should be private. The only time I expect to see other server data is when the admin has given the data knowingly (such as sending it over via discord). I personally feel violated when any software attempts to steal my data, especially when they have a option to disable the mertics yet they steal it anyway ... Jus less. 

I will never have metrics in my software.

File: src/main/java/org/zone/commands/structure/region/flags/player/falldamage/ZoneFlagPlayerFallDamageEnableDisable.java (hunk 11 above)
Comment (mosemister) [reply src/main/java/org/zone/commands/structure/region/flags/player/falldamage/ZoneFlagPlayerFallDamageEnableDisable.java]: ?

File: src/main/java/org/zone/region/group/key/GroupKeys.java [hunk 13]
```diff
@@ -14,29 +14,31 @@
...
     @Override
-    public @NotNull String getKey() {
+    public String getKey() {
         return this.key;
     }
 
     @Override
-    public @NotNull PluginContainer getPlugin() {
+    public PluginContainer getPlugin() {
         return ZonePlugin.getZonesPlugin().getPluginContainer();
```
Comment (mosemister) [inline src/main/java/org/zone/region/group/key/GroupKeys.java]: You may want to add the @NotNull back in

File: pom.xml (hunk 9 above)
Comment (Lukamon24) [reply pom.xml]: oh lmao ok

File: src/main/java/org/zone/region/group/key/GroupKeys.java (hunk 7 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/group/key/GroupKeys.java]: k

File: src/main/java/org/zone/commands/structure/region/flags/player/entitydamage/ZoneFlagEntityDamagePlayerEnableDisable.java [hunk 14]
```diff
@@ -0,0 +1,67 @@
...
+
+    @Override
+    public @NotNull CommandResult run(@NotNull CommandContext commandContext, @NotNull String... args) {
+        boolean enable = commandContext.getArgument(this, ENABLE_DISABLE);
+        Zone zone = commandContext.getArgument(this, ZONE_VALUE);
+        EntityDamagePlayerFlag entityDamagePlayerFlag = zone
+                .getFlag(FlagTypes.ENTITY_DAMAGE_PLAYER_FLAG_TYPE)
+                .orElse(new EntityDamagePlayerFlag());
+        if (enable) {
+            zone.addFlag(FlagTypes.ENTITY_DAMAGE_PLAYER_FLAG_TYPE.createCopyOfDefault());
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/player/entitydamage/ZoneFlagEntityDamagePlayerEnableDisable.java]: This should not add a new one incase the user attempts to add the tag despite already added. While it shouldnt matter much, it always better to use the same instance where possible

File: src/main/java/org/zone/commands/structure/region/flags/player/falldamage/ZoneFlagPlayerFallDamageEnableDisable.java [hunk 15]
```diff
@@ -0,0 +1,68 @@
...
+
+    @Override
+    public @NotNull CommandResult run(@NotNull CommandContext commandContext, @NotNull String... args) {
+        boolean enable = commandContext.getArgument(this, ENABLE_DISABLE);
+        Zone zone = commandContext.getArgument(this, ZONE_VALUE);
+        PlayerFallDamageFlag playerFallDamageFlag = zone
+                .getFlag(FlagTypes.PLAYER_FALL_DAMAGE_FLAG_TYPE)
+                .orElse(new PlayerFallDamageFlag());
+        if (enable) {
+            zone.addFlag(FlagTypes.PLAYER_FALL_DAMAGE_FLAG_TYPE.createCopyOfDefault());
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/player/falldamage/ZoneFlagPlayerFallDamageEnableDisable.java]: Same as before

File: src/main/java/org/zone/region/group/key/GroupKeys.java (hunk 13 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/group/key/GroupKeys.java]: k?

Comment (Lukamon24) [reply src/main/java/org/zone/region/group/key/GroupKeys.java]: oops i mean yes

File: src/main/java/org/zone/commands/structure/region/flags/player/entitydamage/ZoneFlagEntityDamagePlayerEnableDisable.java (hunk 14 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/player/entitydamage/ZoneFlagEntityDamagePlayerEnableDisable.java]: k? wdym

File: src/main/java/org/zone/commands/structure/region/flags/player/falldamage/ZoneFlagPlayerFallDamageEnableDisable.java (hunk 15 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/player/falldamage/ZoneFlagPlayerFallDamageEnableDisable.java]: mm

File: src/main/java/org/zone/region/flag/interact/itemframe/ItemFrameInteractFlagType.java [hunk 16]
```diff
@@ -1,20 +1,15 @@
...
-import java.io.IOException;
-import java.util.Optional;
-
-public class ItemFrameInteractFlagType implements FlagType<ItemFrameInteractFlag> {
+public class ItemFrameInteractFlagType implements FlagType.TaggedFlagType<ItemFrameInteractFlag> {
 
     @Override
     public @NotNull String getName() {
-        return "Interaction with Item Frames";
+        return "Item_frame Interact";
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/interact/itemframe/ItemFrameInteractFlagType.java:12]: How come this change?

Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/interact/itemframe/ItemFrameInteractFlagType.java:12]: oh XD just removed code sowwy

Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/interact/itemframe/ItemFrameInteractFlagType.java:12]: do u want the same?

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java [hunk 17]
```diff
@@ -0,0 +1,43 @@
...
+
+import java.util.Optional;
+
+public class PlayerFallDamageListener {
+
+    @Listener
+    public void onPlayerFallDamageEvent(CollideBlockEvent.Fall event) {
+
+        if (!(event instanceof Player player)) {
+            return;
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java:21]: A event will never be a player

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java [hunk 18]
```diff
@@ -0,0 +1,43 @@
...
+
+        Optional<DamageSource> opDamageSource = event.cause().first(DamageSource.class);
+        if (opDamageSource.isEmpty() || opDamageSource.get().equals(DamageSources.FALLING)) {
+            return;
+        }
+
+        Optional<Zone> opZone = ZonePlugin
+                .getZonesPlugin()
+                .getZoneManager()
+                .getPriorityZone(((Player) event).world(), ((Player) event).position());
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java]: A event will never a  player

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java (hunk 17 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java:21]: emm so? remove that eh

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java (hunk 18 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java]: bruh

File: src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java [hunk 19]
```diff
@@ -0,0 +1,43 @@
...
+import org.zone.ZonePlugin;
+import org.zone.region.Zone;
+import org.zone.region.group.Group;
+import org.zone.region.group.key.GroupKeys;
+
+import java.util.Optional;
+
+public class PlayerFallDamageListener {
+
+    @Listener
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/falldamage/PlayerFallDamageListener.java:17]: Why that event. Thats when a block falls?

File: src/main/java/org/zone/region/group/key/GroupKeys.java [hunk 20]
```diff
@@ -14,24 +14,26 @@
...
 
     @Override
-    public @NotNull String getName() {
+    public String getName() {
         return this.name;
     }
 
     @Override
-    public @NotNull String getKey() {
+    public String getKey() {
```
Comment (mosemister) [inline src/main/java/org/zone/region/group/key/GroupKeys.java]: Please add @NotNull back. Intellij should complain at you for not having it

Comment (Lukamon24) [reply src/main/java/org/zone/region/group/key/GroupKeys.java]: oh yes

File: src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerListener.java [hunk 21]
```diff
@@ -0,0 +1,35 @@
...
+
+public class EntityDamagePlayerListener {
+    @Listener
+    public void onEntityDamageEvent(DamageEntityEvent event) {
+
+        if (!(event.entity() instanceof Player player)) {
+            return;
+        }
+
+        Optional<Zone> opZone = ZonePlugin
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerListener.java:29]: Im not seeing a check for damaged by another entity

File: src/main/java/org/zone/region/group/key/GroupKeys.java [hunk 22]
```diff
@@ -14,11 +14,13 @@
...
-    INTERACT_ITEMFRAME("interact_itemframe",
-                       "Prevent players from interacting an itemframe in your zone");
+    INTERACT_ITEMFRAME("interact_itemframe", "Prevent players from interacting an itemframe in " +
+            "your zone"),
+    ENTITY_DAMAGE_PLAYER("entity_damage_player", "Prevent damage from any other entity"),
+    PLAYER_FALL_DAMAGE("player_fall_damage", "Prevent player  fall damage");
 
-    private final @NotNull String name;
-    private final @NotNull String key;
+    private final String name;
```
Comment (mosemister) [inline src/main/java/org/zone/region/group/key/GroupKeys.java]: Please add @NotNull back to these

File: src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerListener.java (hunk 21 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/player/entitydamage/EntityDamagePlayerListener.java:29]: oops

File: src/main/java/org/zone/region/group/key/GroupKeys.java (hunk 22 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/group/key/GroupKeys.java]: ohk

File: src/main/java/org/zone/ZonePlugin.java [hunk 23]
```diff
@@ -29,10 +34,11 @@
 import org.zone.region.flag.move.player.leaving.LeavingFlagListener;
 import org.zone.region.flag.move.player.preventing.PreventPlayersListener;
 import org.zone.region.group.key.GroupKeyManager;
-import org.zone.utils.Messages;
 
 import java.io.File;
 
+import static org.spongepowered.api.Sponge.eventManager;
```
Comment (mosemister) [inline src/main/java/org/zone/ZonePlugin.java]: Should not have static imports

File: src/main/java/org/zone/ZonePlugin.java [hunk 24]
```diff
@@ -110,7 +116,8 @@ public void onConstructor(ConstructPluginEvent event) {
     }
 
     private void registerListeners() {
-        EventManager eventManager = Sponge.eventManager();
+
+        EventManager eventManager = eventManager();
         eventManager.registerListeners(this.plugin, new PlayerListener());
```
Comment (mosemister) [inline src/main/java/org/zone/ZonePlugin.java:119]: Why?

File: src/main/java/org/zone/ZonePlugin.java (hunk 23 above)
Comment (Lukamon24) [reply src/main/java/org/zone/ZonePlugin.java]: ayoo wtf that's not mine...

File: src/main/java/org/zone/ZonePlugin.java (hunk 24 above)
Comment (Lukamon24) [reply src/main/java/org/zone/ZonePlugin.java:119]: yo wtf how did that change

**Review by mosemister — APPROVED** [review]
Looks good

**Comment by Lukamon24** [comment]
oi link

**Comment by Lukamon24** [comment]
meow?

**Comment by Lukamon24** [comment]
Closes #37

**Comment by Lukamon24** [comment]
damn nah

**Comment by Lukamon24** [comment]
noice
