### PR TITLE
Fixed bugs not finished perms still ;c

### LINKED ISSUE #113: [Bug] Fall flag implements AffectsPlayer
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> Fall flag should implement ``Flag.AffectsPlayer``

### LINKED ISSUE #120: [Bug] Entering prevented zone will give greetings message
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> When entering a zone you are not allowed to via the prevention flag, the prevention flag will kick in and kick the player out (expected). However the player gets the greeting message on every attempt

## How to reproduce?

>> Enable greetings message and the prevention flag. Ensure you do not have permission to enter zone. Attempt to enter zone

## Extra info

By lowering the priority of the greetings message and ensuring that the greeting message does not run when the event is cancelled, then the result should be expected

### LINKED ISSUE #121: [Bug] No set group for attack damage
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> The command ``/zone region <zoneid> flag damage attack set group <groupid>`` is missing

## How to reproduce?

>> Launch the plugin

### LINKED ISSUE #123: [Bug] No view command for fall damage
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> No command for ``zone region <zoneId> flag damage fall view``

## How to reproduce?

>> Launch the plugin

### LINKED ISSUE #124: [Bug] No view command for damage attack
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> No command of ``zone region <zoneid> flag damage attack view``

## How to reproduce?

>> Launch the plugin

### LINKED ISSUE #126: [Bug] Message is wrong
# Bug Report

## Version info

Zone Version: 1.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug
- Greetings message is wrong, instead of being `Message: ...` it's `Message: Message: ...`

## How to reproduce?
- Change the messages in the Messages class
>> How to cause the bug
- Run the `/zone region flag [zoneId] greetings view` command

### Crash report?

```txt
Paste crash report here if possible
```

### LINKED ISSUE #130: [Bug] Monster Prevention doesnt prevent spawning
# Bug Report

## Version info

Zone Version: 1.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> When monster prevention is enabled, monsters can still spawn inside the zone, however cannot move. They should not be able to spawn if this flag is enabled

## How to reproduce?

>> Enable the monster prevention, set time to night, find a monster spawn

### LINKED ISSUE #131: [Bug] Player prevention allows disallowed players to login to zone
# Bug Report

## Version info

Zone Version: x.x.x.x
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> When a player logs in and spawns inside a zone they do not have access to, they are then stuck. 

## How to reproduce?

>> create a area, stand inside the area, leave the area. You are now stuck

## Extra info

If the player logs to a location they cannot access or is stuck, then teleport them outside the zone to a area they can stand in, failing that, teleport them to the world spawn

### PR DESCRIPTION
**Pull request by Lukamon24**
Done ;P not done

### CODE REVIEW

File: src/main/java/org/zone/commands/structure/region/flags/damage/attack/ZoneFlagDamageAttackView.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+    @Override
+    public @NotNull Optional<String> getPermissionNode() {
+        return Optional.empty();
+    }
+
+    @Override
+    public @NotNull CommandResult run(@NotNull CommandContext commandContext,
+                                      @NotNull String... args) {
+        Zone zone = commandContext.getArgument(this, ZONE_VALUE);
+        @NotNull PlayerFallDamageFlag playerFallDamageFlag = zone
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/damage/attack/ZoneFlagDamageAttackView.java]: Is this local variable used? (Line 50)

Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/damage/attack/ZoneFlagDamageAttackView.java]: Yeah

File: src/main/java/org/zone/commands/structure/region/flags/damage/fall/ZoneFlagPlayerFallDamageView.java [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+    public @NotNull Optional<String> getPermissionNode() {
+        return Optional.empty();
+    }
+
+    @Override
+    public @NotNull CommandResult run(@NotNull CommandContext commandContext,
+                                      @NotNull String... args) {
+        Zone zone = commandContext.getArgument(this, ZONE_VALUE);
+        @NotNull EntityDamagePlayerFlag entityDamagePlayerFlag = zone
+                .getFlag(FlagTypes.ENTITY_DAMAGE_PLAYER_FLAG_TYPE)
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/damage/fall/ZoneFlagPlayerFallDamageView.java]: Is this local variable used? Line 51

File: src/main/java/org/zone/commands/structure/region/flags/entry/monster/ZoneFlagMonsterEntryViewCommand.java [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+    public @NotNull Optional<String> getPermissionNode() {
+        return Optional.empty();
+    }
+
+    @Override
+    public @NotNull CommandResult run(@NotNull CommandContext commandContext,
+                                      @NotNull String... args) {
+        Zone zone = commandContext.getArgument(this, ZONE_VALUE);
+        PreventMonsterFlag preventMonsterFlag = zone
+                .getFlag(FlagTypes.PREVENT_MONSTER)
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/entry/monster/ZoneFlagMonsterEntryViewCommand.java]: Is this local variable used? Line 52

File: src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntryViewCommand.java [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+    @Override
+    public @NotNull Optional<String> getPermissionNode() {
+        return Optional.empty();
+    }
+
+    @Override
+    public @NotNull CommandResult run(@NotNull CommandContext commandContext,
+                                      @NotNull String... args) {
+        Zone zone = commandContext.getArgument(this, ZONE_VALUE);
+        @NotNull PreventPlayersFlag preventPlayersFlag = zone
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntryViewCommand.java]: Is this local variable used? Line 49

File: src/main/java/org/zone/commands/structure/region/flags/damage/attack/ZoneFlagDamageAttackView.java (hunk 1 above)
Comment (mosemister) [reply src/main/java/org/zone/commands/structure/region/flags/damage/attack/ZoneFlagDamageAttackView.java]: Where? what line number?

File: src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntrySetEnabledCommand.java [hunk 5]
```diff
@@ -31,6 +31,7 @@
         return Arrays.asList(new ExactArgument("region"),
                              new ExactArgument("flag"),
                              ZONE_VALUE,
+                             new ExactArgument("player"),
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntrySetEnabledCommand.java]: Can we make entry before player?

If we had it player first, it means that flags that affect both players and something else, we would need to create two commands to handle the consistanty, so my stating the player at the flag part, it means that we dont seperate all flags, just the one

File: src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntrySetGroupCommand.java [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+                                                                   new ZoneArgument.ZoneArgumentPropertiesBuilder());
+    public static final ZoneGroupArgument GROUP = new ZoneGroupArgument("groupId", ZONE_VALUE);
+
+    @Override
+    public @NotNull List<CommandArgument<?>> getArguments() {
+        return Arrays.asList(new ExactArgument("region"),
+                             new ExactArgument("flag"),
+                             ZONE_VALUE,
+                             new ExactArgument("player"),
+                             new ExactArgument("entry"),
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntrySetGroupCommand.java]: Same as above

File: src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java [hunk 7]
```diff
@@ -36,4 +37,23 @@ public void onMonsterMoveForMonsterPrevention(MoveEntityEvent event,
         }
         event.setCancelled(true);
     }
-}
+
+    @Listener
+    public void onMonsterSpawnEvent(SpawnEntityEvent event, Monster monster) {
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java]: Remove the ``Monster monster``

Events can only take 1 parameter (that being the event) if you specify more parameters, you need a annotation

File: src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java [hunk 8]
```diff
@@ -36,4 +37,23 @@ public void onMonsterMoveForMonsterPrevention(MoveEntityEvent event,
...
+        boolean contains = event
+                .entities()
+                .stream()
+                .filter(entity ->
+                                entity instanceof Monster)
+                .anyMatch(entity -> {
+                 Optional<Zone> opZone = ZonePlugin
+                    .getZonesPlugin()
+                    .getZoneManager()
+                    .getPriorityZone(monster.world(), monster.position());
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java]: This should be ``entity`` not ``monster``

File: src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java [hunk 9]
```diff
@@ -53,4 +58,142 @@ public void onPlayerMove(MoveEntityEvent event, @Getter("entity") Player player)
...
+                .getZonesPlugin()
+                .getZoneManager()
+                .getPriorityZone(joinevent.player().world(), joinevent.player().position());
+
+        if (opZone.isEmpty()) {
+            return;
+        }
+
+        if (!(opZone.get().containsFlag(FlagTypes.PREVENT_PLAYERS))) {
+            return;
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java]: This is checked in the line ``flag.isEmpty`` so you can remove this if statement completely

File: src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java [hunk 10]
```diff
@@ -53,4 +58,142 @@ public void onPlayerMove(MoveEntityEvent event, @Getter("entity") Player player)
...
+        }
+
+        Optional<PreventPlayersFlag> flag = opZone
+                .get()
+                .getFlag(FlagTypes.PREVENT_PLAYERS);
+        if (flag.isEmpty()) {
+            return;
+        }
+        if (flag.get().hasPermission(opZone.get(),serverPlayer.uniqueId())) {
+            Optional<Vector3i> opTeleportPos = opZone
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java]: You know I hate nested if statements. 

```java
        if (!flag.get().hasPermission(opZone.get(),serverPlayer.uniqueId())) {
            return;
        }
```

reads so much more clear

File: src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java [hunk 11]
```diff
@@ -53,4 +58,142 @@ public void onPlayerMove(MoveEntityEvent event, @Getter("entity") Player player)
...
+                                .world()
+                                .highestPositionAt(position);
+                    });
+            if (opTeleportPos.isPresent()) {
+                serverPlayer.setPosition(opTeleportPos.get().toDouble());
+            }else {
+                serverPlayer.setPosition(serverPlayer.world().properties().spawnPosition().toDouble());
+            }
+        }else {
+            return;
```
Comment (mosemister) [inline src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java:80]:
```java
} else {
    return
}
```

When its the last line, is the same as just ``}``

**Review by mosemister — CHANGES_REQUESTED** [review]
A few small issues, nothing too big

File: src/main/java/org/zone/commands/structure/region/flags/damage/attack/ZoneFlagDamageAttackView.java (hunk 1 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/damage/attack/ZoneFlagDamageAttackView.java]: oh wait not used

File: src/main/java/org/zone/commands/structure/region/flags/damage/fall/ZoneFlagPlayerFallDamageView.java (hunk 2 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/damage/fall/ZoneFlagPlayerFallDamageView.java]: nope

File: src/main/java/org/zone/commands/structure/region/flags/entry/monster/ZoneFlagMonsterEntryViewCommand.java (hunk 3 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/entry/monster/ZoneFlagMonsterEntryViewCommand.java]: nope

File: src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntryViewCommand.java (hunk 4 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntryViewCommand.java]: nope

File: src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntrySetEnabledCommand.java (hunk 5 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntrySetEnabledCommand.java]: ok..

File: src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntrySetGroupCommand.java (hunk 6 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntrySetGroupCommand.java]: ye ok

File: src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java (hunk 7 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java]: ok...

File: src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java (hunk 8 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java]: why?

File: src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java (hunk 9 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java]: k

File: src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java (hunk 10 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java]: XD

File: src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java (hunk 11 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java:80]: mmm

**Comment by Lukamon24** [comment]
; )

File: src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java (hunk 10 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java]: emm so else not needed?

File: src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java (hunk 11 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java:80]: but is this needed/

File: src/main/java/org/zone/commands/structure/region/flags/damage/attack/ZoneFlagDamageAttackView.java (hunk 1 above)
Comment (mosemister) [reply src/main/java/org/zone/commands/structure/region/flags/damage/attack/ZoneFlagDamageAttackView.java]: Then please remove

File: src/main/java/org/zone/commands/structure/region/flags/entry/monster/ZoneFlagMonsterEntryEnabledCommand.java [hunk 12]
```diff
@@ -0,0 +1,70 @@
...
+                                                                   new ZoneArgument.ZoneArgumentPropertiesBuilder());
+    public static final BooleanArgument ENABLED = new BooleanArgument("enabledValue", "enable",
+                                                                      "disable");
+
+    @Override
+    public @NotNull List<CommandArgument<?>> getArguments() {
+        return Arrays.asList(new ExactArgument("region"),
+                             new ExactArgument("flag"),
+                             ZONE_VALUE,
+                             new ExactArgument("monster"),
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/entry/monster/ZoneFlagMonsterEntryEnabledCommand.java]: Mind moving the Monster argument under Entry?

File: src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntryViewCommand.java [hunk 13]
```diff
@@ -0,0 +1,67 @@
...
+public class ZoneFlagEntryViewCommand implements ArgumentCommand {
+
+    public static final ZoneArgument ZONE_VALUE = new ZoneArgument("zoneId");
+    public static final OptionalArgument<String> VIEW = new OptionalArgument<>(new ExactArgument(
+            "view"), (String) null);
+
+    @Override
+    public @NotNull List<CommandArgument<?>> getArguments() {
+        return Arrays.asList(new ExactArgument("region"), new ExactArgument("flag"), ZONE_VALUE,
+                             new ExactArgument("player"), new ExactArgument("entry"), VIEW);
```
Comment (mosemister) [inline src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntryViewCommand.java]: Can you swap player and entry over

File: src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java (hunk 8 above)
Comment (mosemister) [reply src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java]: Because this event doesnt have a Monster in the cause, therefore you should remove the monster parameter. Therefore your left with the entity argument from the ``anyMatch``

File: src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java (hunk 11 above)
Comment (mosemister) [reply src/main/java/org/zone/region/flag/entity/player/move/preventing/PreventPlayersListener.java:80]: Thats the point that i just said. Its not.

File: src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java (hunk 8 above)
Comment (Lukamon24) [reply src/main/java/org/zone/region/flag/entity/monster/move/MonsterPreventionListener.java]: k

File: src/main/java/org/zone/commands/structure/region/flags/entry/monster/ZoneFlagMonsterEntryEnabledCommand.java (hunk 12 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/entry/monster/ZoneFlagMonsterEntryEnabledCommand.java]: did it long ago

File: src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntryViewCommand.java (hunk 13 above)
Comment (Lukamon24) [reply src/main/java/org/zone/commands/structure/region/flags/entry/player/ZoneFlagEntryViewCommand.java]: same as above

**Review by mosemister — APPROVED** [review]
Looks good

**Comment by Lukamon24** [comment]
; )
